OPENROUTER_API_KEY = "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"
GEMINI_API_KEY = "AIzaSyCPMEUr3wq3vpCc1zuPEsdZNbL5NV4S3rI"
MISTRAL_API_KEY = "4TahFPgYzmYNQtsJ8sJntWzVAd6WOEGZ"
